# Generated by Django 3.0 on 2020-02-16 15:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='contact_date',
            field=models.DateTimeField(blank=True, verbose_name=datetime.datetime(2020, 2, 16, 21, 24, 57, 429538)),
        ),
    ]
