# Generated by Django 3.0 on 2020-02-16 15:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_auto_20200216_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='contact_date',
            field=models.DateTimeField(null=True, verbose_name=datetime.datetime.now),
        ),
    ]
